(PARAGRAPH :id "para-0" :metadata {:position 0 :length 1147}
  (SENTENCE :id "para-0-s0" :metadata {:position 0 :length 99}
    (PHRASE :id "para-0-s0-p0" :metadata {:position 0}
      (PRON "Longtemps")
      (PUNCT ",")
    )
    (PHRASE :id "para-0-s0-p2" :metadata {:position 2}
      (PRON "je")
      (V "me")
      (V "suis")
      (V "couché")
      (P "de")
      (N "bonne")
      (N "heure")
      (PUNCT ".")
    )
  )
  (SENTENCE :id "para-0-s1" :metadata {:position 1 :length 240}
    (PHRASE :id "para-0-s1-p0" :metadata {:position 0}
      (N "Parfois")
      (PUNCT ",")
    )
    (PHRASE :id "para-0-s1-p2" :metadata {:position 2}
      (P "à")
      (N "peine")
      (DET "ma")
      (N "bougie")
      (V "éteinte")
      (PUNCT ",")
    )
    (PHRASE :id "para-0-s1-p4" :metadata {:position 4}
      (DET "mes")
      (N "yeux")
      (V "se")
      (V "fermaient")
      (P "si")
      (N "vite")
      (P "que")
      (PRON "je")
      (PRON "n")
      (V "avais")
      (P "pas")
      (DET "le")
      (N "temps")
      (P "de")
      (V "me")
      (V "dire")
      (PUNCT ":")
    )
    (PHRASE :id "para-0-s1-p6" :metadata {:position 6}
      (PRON "Je")
      (PRON "m")
      (V "endors")
      (PUNCT ".")
    )
  )
  (SENTENCE :id "para-0-s2" :metadata {:position 2 :length 806}
    (PHRASE :id "para-0-s2-p0" :metadata {:position 0}
      (CONJ "Et")
      (PUNCT ",")
    )
    (PHRASE :id "para-0-s2-p2" :metadata {:position 2}
      (DET "une")
      (N "demi")
      (PUNCT "-")
      (N "heure")
      (P "après")
      (PUNCT ",")
    )
    (PHRASE :id "para-0-s2-p4" :metadata {:position 4}
      (DET "la")
      (N "pensée")
      (P "qu")
      (PRON "il")
      (V "était")
      (N "temps")
      (P "de")
      (V "chercher")
      (DET "le")
      (N "sommeil")
      (PRON "m")
      (V "éveillait")
      (PUNCT ";")
    )
    (PHRASE :id "para-0-s2-p6" :metadata {:position 6}
      (PRON "je")
      (V "voulais")
      (V "poser")
      (DET "le")
      (N "volume")
      (P "que")
      (PRON "je")
      (V "croyais")
      (V "avoir")
      (N "encore")
      (P "dans")
      (DET "les")
      (N "mains")
      (CONJ "et")
      (V "souffler")
      (DET "ma")
      (N "lumière")
      (PUNCT ";")
    )
    (PHRASE :id "para-0-s2-p8" :metadata {:position 8}
      (PRON "je")
      (PRON "n")
      (V "avais")
      (P "pas")
      (V "cessé")
      (P "en")
      (V "dormant")
      (P "de")
      (V "faire")
      (DET "des")
      (N "réflexions")
      (P "sur")
      (P "ce")
      (P "que")
      (PRON "je")
      (V "venais")
      (P "de")
      (V "lire")
      (PUNCT ",")
    )
    (PHRASE :id "para-0-s2-p10" :metadata {:position 10}
      (CONJ "mais")
      (DET "ces")
      (N "réflexions")
      (V "avaient")
      (V "pris")
      (DET "un")
      (N "tour")
      (DET "un")
      (N "peu")
      (N "particulier")
      (PUNCT ";")
    )
    (PHRASE :id "para-0-s2-p12" :metadata {:position 12}
      (PRON "il")
      (V "me")
      (V "semblait")
      (P "que")
      (PRON "j")
      (V "étais")
      (PRON "moi")
      (PUNCT "-")
      (N "même")
      (P "ce")
      (P "dont")
      (V "parlait")
      (DET "l")
      (N "ouvrage")
      (PUNCT ":")
    )
    (PHRASE :id "para-0-s2-p14" :metadata {:position 14}
      (DET "une")
      (N "église")
      (PUNCT ",")
    )
    (PHRASE :id "para-0-s2-p16" :metadata {:position 16}
      (DET "un")
      (N "quatuor")
      (PUNCT ",")
    )
    (PHRASE :id "para-0-s2-p18" :metadata {:position 18}
      (DET "la")
      (N "rivalité")
      (P "de")
      (N "François")
      (N "Ier")
      (CONJ "et")
      (P "de")
      (N "Charles")
      (N "Quint")
      (PUNCT ".")
    )
  )
)
(PARAGRAPH :id "para-1" :metadata {:position 1 :length 1147}
  (SENTENCE :id "para-1-s0" :metadata {:position 0 :length 129}
    (PHRASE :id "para-1-s0-p0" :metadata {:position 0}
      (DET "Cette")
      (N "croyance")
      (V "survivait")
      (P "pendant")
      (N "quelques")
      (N "secondes")
      (P "à")
      (DET "mon")
      (N "réveil")
      (PUNCT ";")
    )
    (PHRASE :id "para-1-s0-p2" :metadata {:position 2}
      (PRON "elle")
      (P "ne")
      (V "choquait")
      (P "pas")
      (DET "ma")
      (N "raison")
      (CONJ "mais")
      (V "pesait")
      (P "comme")
      (DET "des")
      (N "écailles")
      (P "sur")
      (DET "mes")
      (N "yeux")
      (CONJ "et")
      (DET "les")
      (V "empêchait")
      (P "de")
      (V "se")
      (V "rendre")
      (N "compte")
      (P "que")
      (DET "le")
      (N "bougeoir")
      (PRON "n")
      (V "était")
      (P "plus")
      (V "allumé")
      (PUNCT ".")
    )
  )
  (SENTENCE :id "para-1-s1" :metadata {:position 1 :length 102}
    (PHRASE :id "para-1-s1-p0" :metadata {:position 0}
      (N "Puis")
      (PRON "elle")
      (V "commençait")
      (P "à")
      (V "me")
      (V "devenir")
      (N "inintelligible")
      (PUNCT ",")
    )
    (PHRASE :id "para-1-s1-p2" :metadata {:position 2}
      (P "comme")
      (P "après")
      (DET "la")
      (N "métempsycose")
      (DET "les")
      (N "pensées")
      (P "d")
      (DET "une")
      (N "existence")
      (N "antérieure")
      (PUNCT ";")
    )
  )
  (SENTENCE :id "para-1-s2" :metadata {:position 2 :length 60}
    (PHRASE :id "para-1-s2-p0" :metadata {:position 0}
      (DET "le")
      (N "sujet")
      (P "du")
      (N "livre")
      (V "se")
      (V "détachait")
      (P "de")
      (PRON "moi")
      (PUNCT ",")
    )
    (PHRASE :id "para-1-s2-p2" :metadata {:position 2}
      (PRON "j")
      (V "étais")
      (N "libre")
      (P "de")
      (PRON "m")
      (PRON "y")
      (V "appliquer")
      (CONJ "ou")
      (P "non")
      (PUNCT ";")
    )
  )
  (SENTENCE :id "para-1-s3" :metadata {:position 3 :length 178}
    (PHRASE :id "para-1-s3-p0" :metadata {:position 0}
      (N "aussitôt")
      (PRON "je")
      (V "recouvrais")
      (DET "la")
      (N "vue")
      (CONJ "et")
      (PRON "j")
      (V "étais")
      (N "bien")
      (V "étonné")
      (P "de")
      (V "trouver")
      (N "autour")
      (P "de")
      (PRON "moi")
      (DET "une")
      (N "obscurité")
      (PUNCT ",")
    )
    (PHRASE :id "para-1-s3-p2" :metadata {:position 2}
      (N "douce")
      (CONJ "et")
      (N "reposante")
      (P "pour")
      (DET "mes")
      (N "yeux")
      (PUNCT ",")
    )
    (PHRASE :id "para-1-s3-p4" :metadata {:position 4}
      (CONJ "mais")
      (N "peut")
      (PUNCT "-")
      (V "être")
      (P "plus")
      (N "encore")
      (P "pour")
      (DET "mon")
      (N "esprit")
      (PUNCT ",")
    )
    (PHRASE :id "para-1-s3-p6" :metadata {:position 6}
      (P "à")
      (P "qui")
      (PRON "elle")
      (V "apparaissait")
      (P "comme")
      (DET "une")
      (N "chose")
      (P "sans")
      (N "cause")
      (PUNCT ",")
    )
    (PHRASE :id "para-1-s3-p8" :metadata {:position 8}
      (N "incompréhensible")
      (PUNCT ",")
    )
    (PHRASE :id "para-1-s3-p10" :metadata {:position 10}
      (P "comme")
      (DET "une")
      (N "chose")
      (N "vraiment")
      (N "obscure")
      (PUNCT ".")
    )
  )
)